---
"on":
  push:
    branches-ignore:
      - main

jobs:
  createPullRequest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: actions/create-pull-request@1.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: "AutoPR: merge ${{ github.ref_name }} to main: ${{ github.event.head_commit.message }}"
